config/routes.rb
Rails.application.routes.draw do
  resources :images
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      redirect_to images_path
    else
      render :new
    end
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      sleep(3) # S3への画像反映のタイムラグを考慮して3秒待機
      redirect_to image_url(@image)
    else
      render :edit
    end
  end

  def show
    @image = Image.find(params[:id])
    # 参照先のS3オブジェクトURLを作成
   @image_url = "https://RESIZE_BUCKET_NAME.s3-ap-northeast-1.amazonaws.com/store/#{@image.image.key}-thumbnail.#{@image.image.content_type.split('/').pop}"
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to images_path
  end

  private

  def image_params
    params.require(:image).permit(:name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/edit.html.erb
<h1>Images#edit</h1>
<%= form_with model: @image, local: true do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :image %>
  <%= form.file_field :image %>
  <p><%= form.submit "Edit" %></p>
<% end %>

app/views/images/index.html.erb
<h1>Images#index</h1>
<div>
  <%= link_to "新規作成", new_image_path %>
</div>
<% @images.each do |image| %>
  <h2><%= image.name %></h2>
  <%= link_to "詳細", image_path(image) %>
  <%= link_to "削除", image_path(image), method: :delete %>
<% end %>

app/views/images/new.html.erb
<h1>Images#new</h1>
<%= form_with model: @image, local: true do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :image %>
  <%= form.file_field :image %>
  <p><%= form.submit "Upload" %></p>
<% end %>

app/views/images/show.html.erb
<h1>Images#show</h1>
<h2><%= @image.name %></h2>
<div>
  <%= image_tag @image_url %>
</div>
<p><%= link_to "編集", edit_image_path(@image) %></p>
<p><%= link_to "戻る", images_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageUploadApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>